config/routes.rb
Scorecard::Application.routes.draw do
 
    resources :cards

    resources :users 

    

    

end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :user
	validates :id, :presence => true
	validates :date, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :cards
    validates :name, :presence => true,
        :length => { :minimum => 5 } 
    validates_presence_of :country
    validates_uniqueness_of :name
    accepts_nested_attributes_for :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Awesome card creation, bro!' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
    @user.cards.build
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>

 <table>
<tr>
<td> <div class="field">
    <%= f.label :SAT_overallQoL %><br />
    <%= f.number_field :SAT_overallQoL %>
  </div></td>
  <td>
 <div class="field">
    <%= f.label :SAT_overallQoL_C %><br />
    <%= f.text_field :SAT_overallQoL_C %>
  </div>
 </td>
  </tr>
  <tr>
<td>
   
   <div class="field">
    <%= f.label :SAT_prospects %><br />
    <%= f.number_field :SAT_prospects %>
  </div>
  <td>
    <div class="field">
    <%= f.label :SAT_prospects_C %><br />
    <%= f.text_field :SAT_prospects_C %>
  </div>
  </td>
  </tr> 

<tr>
<td>

  <div class="field">
    <%= f.label :PROF_principalActivity %><br />
    <%= f.number_field :PROF_principalActivity %>
  </div>
  
  <td><div class="field">
    <%= f.label :PROF_principalActivity_C %><br />
    <%= f.text_field :PROF_principalActivity_C %>
  </div></td>
  </tr>
  <div class="field">
    <%= f.label :PROF_sideProjects %><br />
    <%= f.number_field :PROF_sideProjects %>
  </div>
  <td>
    <div class="field">
    <%= f.label :PROF_sideProjects_C %><br />
    <%= f.text_field :PROF_sideProjects_C %>
  </div>
   </td>
  </tr>  
   </table>
   <div class="field">
    <%= f.label :PROF_futurePlans %><br />
    <%= f.number_field :PROF_futurePlans %>
  </div>

  
<tr>
<td><div class="field">
    <%= f.label :SOC_friends %><br />
    <%= f.number_field :SOC_friends %>
  </div>
  <td>
  <div class="field">
    <%= f.label :SOC_friends_C %><br />
    <%= f.text_field :SOC_friends_C %>
  </div>
   </td>
  </tr>
  <div class="field">
    <%= f.label :SOC_family %><br />
    <%= f.number_field :SOC_family %>
  </div> <div class="field">
    <%= f.label :SOC_romantic %><br />
    <%= f.number_field :SOC_romantic %>
  </div>
  <div class="field">
    <%= f.label :PHYS_medical %><br />
    <%= f.number_field :PHYS_medical %>
  </div>
  <div class="field">
    <%= f.label :PHYS_fitness %><br />
    <%= f.number_field :PHYS_fitness %>
  </div>
  <div class="field">
    <%= f.label :PHYS_appearance %><br />
    <%= f.number_field :PHYS_appearance %>
  </div>
  <div class="field">
    <%= f.label :FIN_overallHealth %><br />
    <%= f.number_field :FIN_overallHealth %>
  </div>
  <div class="field">
    <%= f.label :FIN_managementOrganization %><br />
    <%= f.number_field :FIN_managementOrganization %>
  </div>
  <div class="field">
    <%= f.label :FIN_futureOutlook %><br />
    <%= f.number_field :FIN_futureOutlook %>
  </div>
 

  

  <div class="field">
    <%= f.label :PROF_futurePlans_C %><br />
    <%= f.text_field :PROF_futurePlans_C %>
  </div>
 
  <div class="field">
    <%= f.label :SOC_family_C %><br />
    <%= f.text_field :SOC_family_C %>
  </div>
  <div class="field">
    <%= f.label :SOC_romantic_C %><br />
    <%= f.text_field :SOC_romantic_C %>
  </div>
  <div class="field">
    <%= f.label :PHYS_medical_C %><br />
    <%= f.text_field :PHYS_medical_C %>
  </div>
  <div class="field">
    <%= f.label :PHYS_fitness_C %><br />
    <%= f.text_field :PHYS_fitness_C %>
  </div>
  <div class="field">
    <%= f.label :PHYS_appearance_C %><br />
    <%= f.text_field :PHYS_appearance_C %>
  </div>
  <div class="field">
    <%= f.label :FIN_overallHealth_C %><br />
    <%= f.text_field :FIN_overallHealth_C %>
  </div>
  <div class="field">
    <%= f.label :FIN_managementOrganization_C %><br />
    <%= f.text_field :FIN_managementOrganization_C %>
  </div>
  <div class="field">
    <%= f.label :FIN_futureOutlook_C %><br />
    <%= f.text_field :FIN_futureOutlook_C %>
  </div>
  <div class="field">
    <%= f.label :goalsLastQuarter %><br />
    <%= f.text_area :goalsLastQuarter %>
  </div>
  <div class="field">
    <%= f.label :resultsLastQuarter %><br />
    <%= f.text_area :resultsLastQuarter %>
  </div>
  <div class="field">
    <%= f.label :goalsNextQuarter %><br />
    <%= f.text_area :goalsNextQuarter %>
  </div>
  <div class="field">
    <%= f.label :metricsNextQuarter %><br />
    <%= f.text_area :metricsNextQuarter %>
  </div>
  <div class="field">
    <%= f.label :potentialFutureGoals %><br />
    <%= f.text_area :potentialFutureGoals %>
  </div>
  <div class="field">
    <%= f.label :potentialFutureGoalIdeas %><br />
    <%= f.text_area :potentialFutureGoalIdeas %>
  </div>
  <div class="field">
    <%= f.label :keyLearnings %><br />
    <%= f.text_area :keyLearnings %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Sat overallqol</th>
    <th>Sat prospects</th>
    <th>Prof principalactivity</th>
    <th>Prof sideprojects</th>
    <th>Prof futureplans</th>
    <th>Soc friends</th>
    <th>Soc family</th>
    <th>Soc romantic</th>
    <th>Phys medical</th>
    <th>Phys fitness</th>
    <th>Phys appearance</th>
    <th>Fin overallhealth</th>
    <th>Fin managementorganization</th>
    <th>Fin futureoutlook</th>
    <th>Sat overallqol c</th>
    <th>Sat prospects c</th>
    <th>Prof principalactivity c</th>
    <th>Prof sideprojects c</th>
    <th>Prof futureplans c</th>
    <th>Soc friends c</th>
    <th>Soc family c</th>
    <th>Soc romantic c</th>
    <th>Phys medical c</th>
    <th>Phys fitness c</th>
    <th>Phys appearance c</th>
    <th>Fin overallhealth c</th>
    <th>Fin managementorganization c</th>
    <th>Fin futureoutlook c</th>
    <th>Goalslastquarter</th>
    <th>Resultslastquarter</th>
    <th>Goalsnextquarter</th>
    <th>Metricsnextquarter</th>
    <th>Potentialfuturegoals</th>
    <th>Potentialfuturegoalideas</th>
    <th>Keylearnings</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.date %></td>
    <td><%= card.SAT_overallQoL %></td>
    <td><%= card.SAT_prospects %></td>
    <td><%= card.PROF_principalActivity %></td>
    <td><%= card.PROF_sideProjects %></td>
    <td><%= card.PROF_futurePlans %></td>
    <td><%= card.SOC_friends %></td>
    <td><%= card.SOC_family %></td>
    <td><%= card.SOC_romantic %></td>
    <td><%= card.PHYS_medical %></td>
    <td><%= card.PHYS_fitness %></td>
    <td><%= card.PHYS_appearance %></td>
    <td><%= card.FIN_overallHealth %></td>
    <td><%= card.FIN_managementOrganization %></td>
    <td><%= card.FIN_futureOutlook %></td>
    <td><%= card.SAT_overallQoL_C %></td>
    <td><%= card.SAT_prospects_C %></td>
    <td><%= card.PROF_principalActivity_C %></td>
    <td><%= card.PROF_sideProjects_C %></td>
    <td><%= card.PROF_futurePlans_C %></td>
    <td><%= card.SOC_friends_C %></td>
    <td><%= card.SOC_family_C %></td>
    <td><%= card.SOC_romantic_C %></td>
    <td><%= card.PHYS_medical_C %></td>
    <td><%= card.PHYS_fitness_C %></td>
    <td><%= card.PHYS_appearance_C %></td>
    <td><%= card.FIN_overallHealth_C %></td>
    <td><%= card.FIN_managementOrganization_C %></td>
    <td><%= card.FIN_futureOutlook_C %></td>
    <td><%= card.goalsLastQuarter %></td>
    <td><%= card.resultsLastQuarter %></td>
    <td><%= card.goalsNextQuarter %></td>
    <td><%= card.metricsNextQuarter %></td>
    <td><%= card.potentialFutureGoals %></td>
    <td><%= card.potentialFutureGoalIdeas %></td>
    <td><%= card.keyLearnings %></td>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(card) %></td>
    <td><%= link_to 'Destroy', card, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @card.date %>
</p>

<p>
  <b>Sat overallqol:</b>
  <%= @card.SAT_overallQoL %>
</p>

<p>
  <b>Sat prospects:</b>
  <%= @card.SAT_prospects %>
</p>

<p>
  <b>Prof principalactivity:</b>
  <%= @card.PROF_principalActivity %>
</p>

<p>
  <b>Prof sideprojects:</b>
  <%= @card.PROF_sideProjects %>
</p>

<p>
  <b>Prof futureplans:</b>
  <%= @card.PROF_futurePlans %>
</p>

<p>
  <b>Soc friends:</b>
  <%= @card.SOC_friends %>
</p>

<p>
  <b>Soc family:</b>
  <%= @card.SOC_family %>
</p>

<p>
  <b>Soc romantic:</b>
  <%= @card.SOC_romantic %>
</p>

<p>
  <b>Phys medical:</b>
  <%= @card.PHYS_medical %>
</p>

<p>
  <b>Phys fitness:</b>
  <%= @card.PHYS_fitness %>
</p>

<p>
  <b>Phys appearance:</b>
  <%= @card.PHYS_appearance %>
</p>

<p>
  <b>Fin overallhealth:</b>
  <%= @card.FIN_overallHealth %>
</p>

<p>
  <b>Fin managementorganization:</b>
  <%= @card.FIN_managementOrganization %>
</p>

<p>
  <b>Fin futureoutlook:</b>
  <%= @card.FIN_futureOutlook %>
</p>

<p>
  <b>Sat overallqol c:</b>
  <%= @card.SAT_overallQoL_C %>
</p>

<p>
  <b>Sat prospects c:</b>
  <%= @card.SAT_prospects_C %>
</p>

<p>
  <b>Prof principalactivity c:</b>
  <%= @card.PROF_principalActivity_C %>
</p>

<p>
  <b>Prof sideprojects c:</b>
  <%= @card.PROF_sideProjects_C %>
</p>

<p>
  <b>Prof futureplans c:</b>
  <%= @card.PROF_futurePlans_C %>
</p>

<p>
  <b>Soc friends c:</b>
  <%= @card.SOC_friends_C %>
</p>

<p>
  <b>Soc family c:</b>
  <%= @card.SOC_family_C %>
</p>

<p>
  <b>Soc romantic c:</b>
  <%= @card.SOC_romantic_C %>
</p>

<p>
  <b>Phys medical c:</b>
  <%= @card.PHYS_medical_C %>
</p>

<p>
  <b>Phys fitness c:</b>
  <%= @card.PHYS_fitness_C %>
</p>

<p>
  <b>Phys appearance c:</b>
  <%= @card.PHYS_appearance_C %>
</p>

<p>
  <b>Fin overallhealth c:</b>
  <%= @card.FIN_overallHealth_C %>
</p>

<p>
  <b>Fin managementorganization c:</b>
  <%= @card.FIN_managementOrganization_C %>
</p>

<p>
  <b>Fin futureoutlook c:</b>
  <%= @card.FIN_futureOutlook_C %>
</p>

<p>
  <b>Goalslastquarter:</b>
  <%= @card.goalsLastQuarter %>
</p>

<p>
  <b>Resultslastquarter:</b>
  <%= @card.resultsLastQuarter %>
</p>

<p>
  <b>Goalsnextquarter:</b>
  <%= @card.goalsNextQuarter %>
</p>

<p>
  <b>Metricsnextquarter:</b>
  <%= @card.metricsNextQuarter %>
</p>

<p>
  <b>Potentialfuturegoals:</b>
  <%= @card.potentialFutureGoals %>
</p>

<p>
  <b>Potentialfuturegoalideas:</b>
  <%= @card.potentialFutureGoalIdeas %>
</p>

<p>
  <b>Keylearnings:</b>
  <%= @card.keyLearnings %>
</p>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<P> Welcome to EC Scorecard App, the key to life management!</P>

Enjoy
<H1> Whatup, mofos? </H1>
<%= link_to "Scorecards", cards_path %>
<%= link_to "Users", users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scorecard</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture_link %><br />
    <%= f.text_field :picture_link %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <%= f.fields_for :cards do |builder| %>
  <%= render '_step_fields.html.erb' %>
<% end %>

<div class="actions">
  <%= f.submit %>
  </div>
<% end %>

app/views/users/_step_fields.html.erb
<div class="field">
  <p>
  <%= f.label :comment, "Answer" %>
  <%= f.text_field :comment %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove" %>
</div></p>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Picture link</th>
    <th>Birthday</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.picture_link %></td>
    <td><%= user.birthday %></td>
    <td><%= user.city %></td>
    <td><%= user.state %></td>
    <td><%= user.country %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Picture link:</b>
  <%= @user.picture_link %>
</p>

<p>
  <b>Birthday:</b>
  <%= @user.birthday %>
</p>

<p>
  <b>City:</b>
  <%= @user.city %>
</p>

<p>
  <b>State:</b>
  <%= @user.state %>
</p>

<p>
  <b>Country:</b>
  <%= @user.country %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>